### ISSUE TITLE
Polygons with holes?

### ISSUE THREAD

**Issue by rowanwins** [geidav/concave-poly-splitter#1]
Gday @geidav 

I was wonder if you knew off the top of your head whether this algorithm would work on polygons with holes. I'm looking at developing something in js - one of my requirements is to support polygons with holes, if your lib can do that I should be able to port your code across. I'm not much good at compiling and testing against C++ code sorry.

Thanks,
Rowan

**Comment by geidav** [comment]
Hi Rowan,

Sorry for my late reply.

I believe the algorithm should work for polygons with holes, but it would become quite a bit more involved because the case distinction machinery would have to consider even more cases. That's because for polygons with holes you need a more complicated data structure to represent them (e.g. a list of vertices for the border of the polygon it-self and lists of vertices for the outline of every hole).

Have you made any progress on that in the meanwhile?

Cheers,
David

**Comment by rowanwins** [comment]
Gday @geidav 

Thanks for the reply, no worries re the slowness :)

I did a bit of looking into your approach and decided it might not be sufficient for my needs, from what I could tell in the source code holes weren't considered and it looked like the splitting line could only contain a single segment. I'm sure most of these these could be overcome with a bit of effort.
 
In the meantime I've just started looking at an alternative algorithm based on [this paper](http://ieeexplore.ieee.org/document/5365438/). It allows the line to have multiple segments and supports a few variations on standard polygons such as polygons with holes and multi-polygons etc. It is also designed to work with polylines (eg with multiple segments). All in all this looked to be closer to what I was after. 

I haven't pushed up my repo yet but hopefully in the next week I'll make a bit more progress, if you're interested I can keep you posted.

Cheers

**Comment by geidav** [comment]
Hi Rowan,

Thanks for letting me know. I wasn't aware of this paper. The abstract sounds a little similar to what I describe in my blog, but I didn't have the time to read it.

Sure. Keep me posted. What is that you need the polygon splitting for?

Cheers,
David

**Comment by rowanwins** [comment]
Will keep you posted! I help maintain the [Turfjs](http://turfjs.org/) library which is basically a collection of modules for various geospatial operations, polygon splitting is something that's been on our radar for a while so I'm finally having a crack!
